name: Update Site Branch

on:
  push:
    branches:
      - main

jobs:
  update-site-branch:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Generate index files
      run: |
        generate_index() {
            local dir="$1"
            local rel_path="${dir#$GITHUB_WORKSPACE}"
            local display_path="/${rel_path#/}"
            local index_file="$dir/index.html"
            local depth="$2"
            
            echo "<!DOCTYPE HTML>
        <html lang=\"en\">
        <head>
        <meta charset=\"utf-8\">
        <title>Directory listing for $display_path</title>
        </head>
        <body>
        <h1>Directory listing for $display_path</h1>
        <hr>
        <ul>" > "$index_file"

            for item in "$dir"/*; do
                local item_name=$(basename "$item")
                if [[ "$item_name" != .* && "$item_name" != *.html ]]; then
                    if [ -d "$item" ]; then
                        echo "<li><a href=\"$item_name/\">$item_name/</a></li>" >> "$index_file"
                    else
                        echo "<li><a href=\"$item_name\">$item_name</a></li>" >> "$index_file"
                    fi
                fi
            done

            # Add release links for folders one level below root
            if [ "$depth" -eq 2 ]; then
                local folder_name=$(basename "$dir")
                local tag=${folder_name// /_}
                local asset_name_1=${folder_name// /.}.-.condensed.audio.zip
                local asset_name_2=${folder_name// /.}.zip
                local owner=$(echo $GITHUB_REPOSITORY | cut -d/ -f1)
                local repo=$(echo $GITHUB_REPOSITORY | cut -d/ -f2)
                
                echo "<li><a href=\"https://github.com/$owner/$repo/releases/download/$tag/$asset_name_1\">$asset_name_1</a></li>" >> "$index_file"
                echo "<li><a href=\"https://github.com/$owner/$repo/releases/download/$tag/$asset_name_2\">$asset_name_2</a></li>" >> "$index_file"
                
                echo "Added release links for $folder_name"
            fi

            echo "</ul>
        <hr>
        </body>
        </html>" >> "$index_file"

            echo "Generated index.html for $display_path"
        }

        process_directory() {
            local dir="$1"
            local depth="$2"
            
            if [[ "$(basename "$dir")" == .* ]]; then
                return
            fi
            
            # Generate index file
            generate_index "$dir" "$depth"
            
            for subdir in "$dir"*/; do
                if [ -d "$subdir" ] && [[ "$(basename "$subdir")" != .* ]]; then
                    process_directory "$subdir" $((depth + 1))
                fi
            done
        }

        process_directory "$GITHUB_WORKSPACE" 0

    - name: Update site branch
      run: |
        # Add all changes
        git add .

        # Commit the changes
        git commit -m "Update site with latest index files and release links"

        # Force push the site branch
        git push -u -f origin main:site
